server:
#  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ssm?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  profiles:
    active: dev,swagger,swapperproperties
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml

